const cartActionsTypes = {
    INITIALIZE_CART: 'INITIALIZE_CART',
    ADD_ITEM_TO_CART_START: 'ADD_ITEM_TO_CART_START', 
    ADD_ITEM_TO_CART_FAILURE: 'ADD_ITEM_TO_CART_FAILURE',
    ADD_ITEM_TO_CART_SUCCESS: 'ADD_ITEM_TO_CART_SUCCESS',
    REMOVE_ITEM_FROM_CART_START: 'REMOVE_ITEM_FROM_CART_START', 
    REMOVE_ITEM_FROM_CART_FAILURE: 'REMOVE_ITEM_FROM_CART_FAILURE',
    REMOVE_ITEM_FROM_CART_SUCCESS: 'REMOVE_ITEM_FROM_CART_SUCCESS',
}

export default cartActionsTypes;