const userActionsTypes = {
    SIGN_IN_START: 'SIGN_IN_START',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS', 
    SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
    SIGN_OUT_START: 'SIGN_OUT_START', 
    SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
    SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',
    CHECK_USER_SESSION: 'CHECK_USER_SESSION',
    SET_PREFERENCES_START: 'SET_PREFERENCES_START',
    SET_PREFERENCES_SUCCESS: 'SET_PREFERENCES_SUCCESS',
    SET_PREFERENCES_FAILURE: 'SET_PREFERENCES_FAILURE',
    SET_FAVORITE_START: 'SET_FAVORITE_START',
    SET_FAVORITE_SUCCESS: 'SET_FAVORITE_SUCCESS',
    SET_FAVORITE_FAILURE: 'SET_FAVORITE_FAILURE', 
    ADD_PLAN_START: 'ADD_PLAN_START', 
    ADD_PLAN_SUCCESS: 'ADD_PLAN_SUCCESS',
}

export default userActionsTypes;